### PR TITLE
Styling

### PR DESCRIPTION
**Pull request by KaraAJC**
Using the current Theme, I incorporated the logo colors to the stylesheet, and added the logo image to the homepage. Looks better, but will be exploring how to use the SVG files, fonts, and looking at specs on other pages that may need further styling. 

_NOTE_
I have two commits related to adding the ReadMe as a gitignore file, because I loaded my own readme for my local repo. let me know if that implementation won't work. 
#6

### CODE REVIEW

**Comment by thejessleigh** [comment]
@KaraAJC I was thinking of adding a ReadMe with notes about the CoC and guidelines for contributing to this repo at some point soon. I'll go ahead and merge in the gitignore stuff, but I might change it later. Does that work?

**Comment by thejessleigh** [comment]
@KaraAJC I think the coloring looks great! However, I think it's a little odd that the logo is featured on the home page but there are no images in the headers on the other pages. Do you think we should add something to the other pages? Maybe `images/logo_files/logoimage.png`? I'm not sure. I'm not a designer. These are just thoughts, I'll ultimately defer to you on this one.

**Comment by KaraAJC** [comment]
@thejessleigh OK! 

The gitignore should allow us to have separate readme files without them conflicting, it would still save/show your readme file, just wouldn't have version history for it, is that still OK? 

In terms of the other pages, I left the logo off because I wanted to try to figure out how to initialize jeckyll so the header and footer would be static templates, and the page content would be dynamic, then leaving the header image on all pages, not just the homepage.

I could probably add the logo image to the top left of all the other pages, let me try that!

**Comment by thejessleigh** [comment]
Okay, cool! That sounds fantastic. Just wanted to check in and get your thoughts. Let me know how adding the logo goes. If you want to put it off until we have Jeckyll or something similar running, I'm happy merging this in now and opening a separate issue for that.

**Comment by KaraAJC** [comment]
@thejessleigh check out the updates I made!
bitmoji

**Comment by thejessleigh** [comment]
Awesome. Merging. Thanks so much for your help on this! If you want to do Jekyll or there's something you think should get done that you haven't gotten around to, just open an issue. Otherwise, I think we're good to go for a while :)

**Pull request merged**
