### PR TITLE
added elstamey to the participants

### PR DESCRIPTION
**Pull request by elstamey**

### CODE REVIEW

**Comment by elstamey** [comment]
I went to the most recent version to add my name.  How do I resolve this merge conflict without the ability to see the conflict?

**Comment by irinarenteria** [comment]
I'm fixing this now, @elstamey.

**Comment by irinarenteria** [comment]
Oh, actually I can't because I'm not an admin. You can see the merge conflict by updating your master, then incorporating the changes from master into your branch.

**Comment by elstamey** [comment]
phew!  text conflicts are more tedious than code conflicts.

**Comment by irinarenteria** [comment]
Good job, @elstamey!

**Comment by thejessleigh** [comment]
Thanks for taking the lead on this @irinarenteria

**Pull request merged**
